In [21]:
import sympy as sp
from sympy import Matrix, pprint
import random
from scipy.spatial.distance import hamming
import itertools

In [22]:
#Customize scipy's hamming distance function
def hamming_distance(a, b):
    if not (isinstance(a, list) and isinstance(b, list)):
        return int(hamming(list(a), list(b)) * len(a))
    return int(hamming(a, b) * len(a))


In [23]:
e1 = Matrix([1, 0, 0, 2, 4])
e2 = Matrix([0, 1, 0, 1, 0])
e3 = Matrix([0, 0, 1, 5, 6])

G = Matrix([e1.transpose(), e2.transpose(), e3.transpose()])
pprint(G)

⎡1  0  0  2  4⎤
⎢             ⎥
⎢0  1  0  1  0⎥
⎢             ⎥
⎣0  0  1  5  6⎦


In [42]:
# Generate a random vector from the space Z^5 modulo 7
def generate_random_vector():
    return Matrix([random.randint(0, 6) for i in range(5)])

# Find the minimal hamming distance
def find_minimal_distance(v: Matrix, G: Matrix):
    min_distance = len(v)
    for x in itertools.product(range(7), repeat=3):
        vector = (Matrix(x).T * G).T % 7
        distance = hamming_distance(v, vector)
        if distance < min_distance:
            min_distance = distance
    return min_distance

# Generate the minimal distance subspace for vector v from Z^5 modulo 7 and generative matrix G
def generate_minimal_distance_subspace(v: Matrix, G: Matrix):
    min_distance = find_minimal_distance(v, G)
    subspace = []
    for x in itertools.product(range(7), repeat=3):
        vector = (Matrix(x).T * G).T % 7
        if hamming_distance(v, vector) == min_distance and vector not in subspace:
            subspace.append(vector)
    return subspace

# Choose random vector from the space
def choose_random_vector(S: list):
    return S[random.randint(0, len(S) - 1)]

# Implement the minimize hamming distance algorithm
def minimize_hamming_distance(v: Matrix, G: Matrix):
    return choose_random_vector(generate_minimal_distance_subspace(v, G))
    # POPRAWIĆ!!!!!




In [43]:
# Test the algorithm
def test(n):
    print("For the clarity of the output, we will display the vectors as transposed.")
    for i in range(n):
        v = generate_random_vector()
        print(f"------------------- Test {i + 1} -----------------------")
        print("v: ", end="")
        pprint(v.transpose())
        print("Minimal distance subspace: ")
        pprint([x.transpose() for x in generate_minimal_distance_subspace(v, G)])
        print("Random vector from the subspace: ", end="")
        pprint(minimize_hamming_distance(v, G).transpose())
        print("--------------------------------------------------")
    pass

test(5)


For the clarity of the output, we will display the vectors as transposed.
------------------- Test 1 -----------------------
v: [2  0  0  6  5]
Minimal distance subspace: 
[[2  0  0  4  1], [2  0  3  5  5], [2  0  6  6  2], [2  1  3  6  5], [2  2  0 
 6  1]]
Random vector from the subspace: [2  2  0  6  1]
--------------------------------------------------
------------------- Test 2 -----------------------
v: [6  3  0  0  5]
Minimal distance subspace: 
[[1  3  6  0  5], [2  3  0  0  1], [3  1  0  0  5], [3  3  0  2  5], [6  2  0 
 0  3], [6  3  0  1  3], [6  3  4  0  6], [6  3  5  5  5], [6  5  5  0  5]]
Random vector from the subspace: [3  1  0  0  5]
--------------------------------------------------
------------------- Test 3 -----------------------
v: [6  4  4  3  2]
Minimal distance subspace: 
[[0  4  4  3  3], [2  4  6  3  2], [5  1  4  3  2], [5  4  4  6  2], [6  0  1 
 3  2], [6  4  1  0  2], [6  4  3  3  0], [6  4  4  1  6], [6  6  4  3  6]]
Random vector from the subspace: [5

In [48]:
np.array(G.T).astype(int)


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [2, 1, 5],
       [4, 0, 6]])

In [ ]:
GF.()

In [45]:
import numpy as np
import galois



GF = galois.GF(7)  # Create a Galois field with 7 elements
A = GF.Random((4, 4))  # Create a random 4x4 matrix over GF(7)
b = GF.Random((4, 1))  # Create a random 4x1 vector over GF(7)
x = np.linalg.solve(A, b)  # Solve the equation Ax = b for x over GF(7)
x

GF([[0],
    [2],
    [5],
    [4]], order=7)

In [62]:
GF7 = galois.GF(7)

v = GF7(np.array(choose_random_vector(generate_minimal_distance_subspace(generate_random_vector(), G))).astype(int))
B = GF7(np.array(G.T).astype(int))

Matrix(B).solve(Matrix(v))


NonInvertibleMatrixError: Matrix det == 0; not invertible.